GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTY1MzM4MjU2OCwiZXhwIjoxNjUzMzkzMzY4fQ.k_WXrFoCVxfF7x0zc_5S3p8SvhHAKPXGKxGWjc2T8DI

###
POST http://localhost:3000/add
Content-Type: application/json

{
    "name": "Jo",
    "surname": "Tunkis",
    "email": "ttunkis@gmail.com",
    "address": "Titnago g. 7",
    "phone": "+37066361183",
    "user_id": 1
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "John",
    "email": "john@john.com",
    "password": "123456"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "mike@mike.com",
    "password": "123456"
}
###