GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTY1MzM4MjU2OCwiZXhwIjoxNjUzMzkzMzY4fQ.k_WXrFoCVxfF7x0zc_5S3p8SvhHAKPXGKxGWjc2T8DI
###
DELETE http://localhost:3000/delete/9
###
POST http://localhost:3000/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjUzNTcwNTA2LCJleHAiOjE2NTM1ODEzMDZ9.2G0J6vikWAyFP5QPxsk9fQ4ucVbC639wmquWFBhSJkI
Content-Type: application/json

{
    "name": "Mike",
    "surname": "Kimiter",
    "email": "mikes@gmail.com",
    "address": "Henry str. 7",
    "phone": "+3458656963"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "emyll@john.com",
    "password": "123456"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "emyll@john.com",
    "password": "123456"
}
###