GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTY1MzM4MjU2OCwiZXhwIjoxNjUzMzkzMzY4fQ.k_WXrFoCVxfF7x0zc_5S3p8SvhHAKPXGKxGWjc2T8DI
###
DELETE http://localhost:3000/delete/9
###
POST http://localhost:3000/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjUzNTU1NzU2LCJleHAiOjE2NTM1NjY1NTZ9.NKulQEPJX5Jm1ooKrBalGuDCWMwvXZZ6-cXyTaNtIZw
Content-Type: application/json

{
    "name": "Jopp",
    "surname": "Tunkis",
    "email": "ttunkis@gmail.com",
    "address": "Titnago g. 7",
    "phone": "+37066361183"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "emyll@john.com",
    "password": "123456"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "emyll@john.com",
    "password": "123456"
}
###